### PR TITLE
unregisterGateway() method added

### PR DESCRIPTION
**Pull request by PayteR**
Now it's not possible to deregister, or substitute `bank_transfer` payment gateway, This method could do that.

### CODE REVIEW

**Comment by rootpd** [comment]
What would be the use case for deregistering the gateway? The reason why `PaymentsModule` is registering it is to always have at least one (default) gateway registered when CRM is installed and not let users get to the point when there's no gateway.

End users will not see it unless you expose it to them and it's meant to be used for backend-created payments (via CRM Admin).

**Comment by rootpd** [comment]
And if you want to substitute it for your own implementation of bank transfer, what would be the reason? Maybe there's a way for you how to do what you need without doing such workaround.

**Comment by PayteR** [comment]
My use case is to extend method Crm\PaymentsModule\Gateways\BankTransfer#begin, because i want to have my custom presenter for bankTransfer

**Comment by rootpd** [comment]
That sounds like a reasonable request, we can rather make that as configuration option of the `bank_transfer` gateway.

**Comment by PayteR** [comment]
Or make redirect by PaymentCompleteRedirectResolver?

**Comment by rootpd** [comment]
That could be a solution too. We're thinking which is more consistent with the rest of the project but since bank transfer already redirects user to `ReturnPresenter`, we may very well allow payment complete resolvers there and let you decide the redirect point there.

**Comment by PayteR** [comment]
Ok, it's up to you.

**Comment by rootpd** [comment]
Hi, this has been added as part of `0.10.0` release, you can hook up to `PaymentCompleteRedirectResolver` and use your own view.

https://github.com/remp2020/crm-payments-module#bank-transfer-landing-page

**Comment by PayteR** [comment]
2 things:
1. redirected presenter must have `VS` GET variable, and NOT!! `variableSymbol`
```
        return [
            ':Payment:Return:bankTransfer',
            [
                'VS' => $payment->variable_symbol,
            ],
        ];
```
2. in `wantsToRedirect` method must be `payment_gateway_id` checked, because without that will be redirected everytime on other gateways
```
        // 6 is bank_transfer gateway
        return $payment->payment_gateway_id === 6;
```

**Comment by rootpd** [comment]
I'm not sure whether I understand.

1. You in your redirect resolver are in control of [where to redirect](https://github.com/remp2020/crm-payments-module/blob/master/src/model/SuccessPageResolver/BankTransferPaymentCompleteRedirectResolver.php#L25) the user (like we are in the default one) and you are in control of the target [presenter action](https://github.com/remp2020/crm-payments-module/blob/master/src/presenters/BankTransferPresenter.php#L14) as well. What _musts_ and _must nots_ are you refering to?
2. The [check is there](https://github.com/remp2020/crm-payments-module/blob/master/src/model/SuccessPageResolver/BankTransferPaymentCompleteRedirectResolver.php#L12). Against gateway code. It's not safe to check against ID as there's no guarantee that other installations have the same ID.

**Comment by PayteR** [comment]
1. it's all about GET param variable, nothing else

**Comment by miroc** [comment]
1. What exactly do you want to achieve? Current implementation of bank redirect resolver passes variable_symbol as a part of URL (id parameter) to [BankTransferPresenter](https://github.com/remp2020/crm-payments-module/blob/master/src/presenters/BankTransferPresenter.php#L14).

**Pull request closed without merging**
