### PR TITLE
Added index to recurrent_payments state column

### PR DESCRIPTION
**Pull request by mikoczy**

### CODE REVIEW

**Comment by rootpd** [comment]
- Just out of curiosity, where do you need this? I don't recall a screen where this would be necessary and all other uses of `recurrent_payments.state` are covered by other conditions and their indices.
- Did MySQL use the index in your scenario? I always have a mixed feelings when adding indices to the enum columns, because MySQL doesn't always use the index even if it's there.

**Comment by mikoczy** [comment]
We need this in the charge command, `getCahrgeablePayments` method, it is a pretty heavy query, execution time is a couple of seconds (5-6).. Yes, mysql used the index..

**Comment by rootpd** [comment]
Merged to the master, I'll close the PR once 0.38 is released.

**Comment by rootpd** [comment]
Merged with https://github.com/remp2020/crm-payments-module/commit/6fc299a781db097d5fa19f3fbf41970e0da0aaa8, closing.

**Pull request closed without merging**
